"""Build dist/Veronica.app: a menu-bar-only .app bundle wrapping `python -m veronica`.

Layout (per docs/superpowers/specs/2026-09-16-veronica-phases-4-6-design.md,
Phase 6):

    Veronica.app/Contents/
        MacOS/Veronica          a tiny native launcher compiled at build time (clang) that dlopen()s the
                                 venv's libpython and runs `python -m veronica` *in-process*. It is a real
                                 Mach-O so macOS attributes the process — and every permission prompt
                                 (Microphone, Screen Recording, Automation, Input Monitoring) — to
                                 "Veronica", not to "python3.12" as a shell-exec launcher would. It bakes
                                 in a PATH that includes the `claude` CLI (Finder/launchd only give the
                                 process /usr/bin:/bin:/usr/sbin:/sbin), cds to <repo>, and exports
                                 VERONICA_BUNDLE_BUILD / VERONICA_APP_BUNDLE before starting Python.
        Info.plist              CFBundleIdentifier io.manik.veronica, LSUIElement, mic/automation usage strings
        Resources/Veronica.icns copied from assets/Veronica.icns (built by scripts/make_icon.py)
        ../veronica-build.json  (next to the .app, NOT inside it — see build_app() for why)
                                 {sha, built_at, dirty, source} from git at build time; the launcher
                                 sets VERONICA_BUNDLE_BUILD pointing here so veronica.version reports
                                 the built commit rather than whatever the repo has moved on to;
                                 it also sets VERONICA_APP_BUNDLE (the .app path) so relaunch /
                                 Start at Login know where the bundle is (argv[0] is __main__.py)
        PkgInfo                 "APPL????"

The build resolves `claude` via `shutil.which("claude")` in the build shell and fails with a clear error
if it isn't found — the Agent SDK needs it at runtime, and by the time the bundle is running under
launchd's minimal PATH it's too late to find it dynamically.

Then `codesign --force --deep -s - dist/Veronica.app` (ad-hoc) so TCC
(microphone/automation) permissions stick to the bundle across rebuilds.

Idempotent: removes any existing dist/Veronica.app first. Run directly:

    uv run python scripts/build_app.py
"""
from __future__ import annotations

import argparse
import contextlib
import json
import os
import plistlib
import shutil
import stat
import subprocess
import sys
import tomllib
from pathlib import Path

from veronica import version as version_mod

REPO = Path(__file__).resolve().parent.parent
BUNDLE_ID = "io.manik.veronica"
APP_NAME = "Veronica"

STUB_SOURCE = r"""
/* Veronica.app launcher — generated by scripts/build_app.py. Embeds CPython
 * (dlopen of the venv's libpython) so the running process IS this bundle's
 * executable and macOS permission prompts say "Veronica". */
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char **argv) {
    setenv("PATH", PATH_PREFIX, 1);
    setenv("LANG", getenv("LANG") ? getenv("LANG") : "en_US.UTF-8", 1);
    setenv("VERONICA_BUNDLE_BUILD", BUILD_JSON, 1);
    setenv("VERONICA_APP_BUNDLE", APP_BUNDLE, 1);
    if (chdir(REPO_DIR) != 0) { perror("veronica launcher: chdir"); return 1; }
    void *lib = dlopen(LIBPYTHON, RTLD_NOW | RTLD_GLOBAL);
    if (!lib) { fprintf(stderr, "veronica launcher: %s\n", dlerror()); return 1; }
    int (*py_main)(int, char **) = (int (*)(int, char **))dlsym(lib, "Py_BytesMain");
    if (!py_main) { fprintf(stderr, "veronica launcher: Py_BytesMain not found\n"); return 1; }
    /* argv[0] = the venv interpreter so CPython finds pyvenv.cfg (site-packages). */
    char **args = calloc((size_t)argc + 3, sizeof(char *));
    int n = 0;
    args[n++] = VENV_PYTHON;
    args[n++] = "-m";
    args[n++] = "veronica";
    for (int i = 1; i < argc; i++) args[n++] = argv[i];
    args[n] = NULL;
    return py_main(n, args);
}
"""


def _libpython_for(venv_python: Path) -> Path:
    """The shared libpython behind a venv's `bin/python` (a symlink into the
    interpreter's install), e.g. <root>/lib/libpython3.12.dylib."""
    real = Path(os.path.realpath(venv_python))
    root = real.parent.parent
    hits = sorted((root / "lib").glob("libpython3*.dylib"))
    if not hits:
        raise RuntimeError(
            f"build_app: no libpython3*.dylib under {root / 'lib'} (resolved from {venv_python}); "
            "the launcher embeds CPython via dlopen and needs the shared library"
        )
    return hits[0]


# The brain CLIs (see veronica/brain/backends): each may live anywhere the
# user's shell happens to find it — a version manager's per-shell directory,
# Homebrew, ~/.local/bin — and the .app starts with launchd's minimal PATH.
# Their real directories are resolved here, at build time, and baked in.
BRAIN_BINARIES = ("claude", "codex", "agy", "copilot")


def _brain_dirs(which=shutil.which) -> list[str]:
    """Directories holding the brain CLIs, deduplicated, in BRAIN_BINARIES
    order. A per-shell path (fnm/nvm "multishell" dirs vanish with the shell
    that made them) is followed to the real install directory first, so the
    baked-in PATH still works tomorrow."""
    dirs: list[str] = []
    for name in BRAIN_BINARIES:
        found = which(name)
        if not found:
            continue
        # resolve() follows the symlink chain: .../fnm_multishells/<pid>/bin/codex
        # -> .../node-versions/vX/installation/lib/node_modules/@openai/codex/bin/codex.js
        real = Path(found).resolve()
        # Ordered, not a set: set iteration over strings is randomised per
        # process, which would reorder PATH and change the signature from one
        # build to the next — the very churn this function must not cause.
        found_dirs = [str(Path(found).parent)]
        found_dirs += [str(real.parent)] if real.suffix != ".js" else _js_bin_dirs(real)
        for candidate in found_dirs:
            if candidate not in dirs and not _ephemeral(candidate):
                dirs.append(candidate)
    return dirs


# fnm builds a per-shell directory whose name carries the shell's pid
# (…/fnm_multishells/85428_1790…/bin). Baking one in makes every build
# differ, which changes the app's code signature — and macOS re-asks for
# Microphone and Screen Recording whenever that changes. The real install
# directory is added alongside it, so dropping these loses nothing.
_EPHEMERAL_PARTS = ("fnm_multishells",)


def _ephemeral(path: str) -> bool:
    return any(part in path for part in _EPHEMERAL_PARTS)


def _js_bin_dirs(real: Path) -> list[str]:
    """For a node CLI shim (…/lib/node_modules/<pkg>/bin/x.js) the directory
    that matters is the node installation's own bin/, not the package's.
    Ordered so the baked PATH is the same on every build."""
    out = [str(real.parent)]
    for parent in real.parents:
        if parent.name == "node_modules" and parent.parent.name == "lib":
            out.append(str(parent.parent.parent / "bin"))
            break
    return out


def _launcher_defines(repo: Path, python: Path, claude_dir: str, build_json: Path, app: Path,
                      libpython: Path, brain_dirs: list[str] | None = None) -> dict[str, str]:
    prefix = [claude_dir, *(brain_dirs or []), str(Path.home() / ".local" / "bin"),
              "/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin"]
    seen: list[str] = []
    for part in prefix:
        if part and part not in seen:
            seen.append(part)
    return {
        "LIBPYTHON": str(libpython),
        "VENV_PYTHON": str(python),
        "REPO_DIR": str(repo),
        "PATH_PREFIX": ":".join(seen),
        "BUILD_JSON": str(build_json),
        "APP_BUNDLE": str(app),
    }


SIGN_IDENTITY = "Veronica Local Signing"


def signing_identity(run=subprocess.run) -> str:
    """The self-signed identity from scripts/make_signing_cert.sh, or "-" for
    ad-hoc. macOS keys Microphone/Screen Recording grants on the signature: an
    ad-hoc one is a hash of the bundle, so any real change re-asks for
    permission, while a certificate keys the grant on bundle id + certificate
    and survives every rebuild. `VERONICA_SIGN_IDENTITY` overrides the name."""
    name = os.environ.get("VERONICA_SIGN_IDENTITY", SIGN_IDENTITY)
    try:
        found = run(["security", "find-identity", "-v", "-p", "codesigning"],
                    capture_output=True, text=True)
    except OSError:
        return "-"
    return name if found.returncode == 0 and name in (found.stdout or "") else "-"


def _compile_with_clang(source: str, out: Path, defines: dict[str, str]) -> None:
    """Default `compiler` for build_app: clang from the Xcode Command Line
    Tools. Each define becomes a C string literal."""
    clang = shutil.which("clang")
    if not clang:
        raise RuntimeError(
            "build_app: clang not found — install the Xcode Command Line Tools "
            "(`xcode-select --install`) to build the native launcher"
        )
    src = out.with_suffix(".c")
    src.write_text(source)
    # ld64 derives LC_UUID from the linked content, so identical inputs give
    # an identical binary — do NOT pass -Wl,-no_uuid to force that: dyld on
    # macOS 27 refuses to load an image with no LC_UUID ("missing LC_UUID
    # load command") and the app won't start at all. Reproducibility comes
    # from the inputs instead (see _brain_dirs).
    argv = [clang, "-O1", "-Wall", "-o", str(out), str(src)]
    for key, value in defines.items():
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        argv.append(f'-D{key}="{escaped}"')
    try:
        done = subprocess.run(argv, capture_output=True, text=True)
        if done.returncode != 0:
            raise RuntimeError(f"build_app: launcher compile failed:\n{done.stderr}")
    finally:
        with contextlib.suppress(OSError):
            src.unlink()


def _read_version(repo: Path) -> str:
    data = tomllib.loads((repo / "pyproject.toml").read_text())
    return data["project"]["version"]


def _info_plist(version: str) -> dict:
    return {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": version,
        "CFBundleShortVersionString": version,
        "CFBundleExecutable": APP_NAME,
        "CFBundleIconFile": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSUIElement": True,
        "LSMinimumSystemVersion": "13.0",
        "NSMicrophoneUsageDescription": "Veronica listens for the wake word and your voice commands.",
        "NSAppleEventsUsageDescription": (
            "Veronica controls Calendar, Mail, Reminders, Notes, Music, Chrome and Safari on your "
            "behalf (reading events, mail, reminders and web pages; creating notes), and uses "
            "System Events to see which app is in front and to type dictation."
        ),
        "NSContactsUsageDescription": (
            "Veronica looks up a contact's phone number or email when you ask her to message "
            "someone by name in Messages."
        ),
        "NSHighResolutionCapable": True,
    }


def build_app(
    *,
    repo: Path = REPO,
    dist_dir: Path | None = None,
    venv_python: Path | None = None,
    codesign_enabled: bool = True,
    claude_bin: Path | str | None = None,
    compiler=None,
    libpython: Path | None = None,
    run=subprocess.run,
) -> Path:
    """Build dist/Veronica.app (or dist_dir/Veronica.app) and return its path.

    `claude_bin` overrides where the `claude` CLI is resolved from (for
    tests); by default it's `shutil.which("claude")` in the build shell, and
    the build fails loudly if that comes back empty. `run` is the subprocess
    runner used to ask git for the build sha (injectable for tests).
    """
    dist_dir = dist_dir or (repo / "dist")
    venv_python = venv_python or (repo / ".venv" / "bin" / "python")

    resolved_claude = claude_bin or shutil.which("claude")
    if not resolved_claude:
        raise RuntimeError(
            "build_app: `claude` CLI not found on PATH. Install/login the Claude Code CLI "
            "before building the app bundle — the Agent SDK needs it at runtime, and the "
            "built .app launches under launchd's minimal PATH "
            "(/usr/bin:/bin:/usr/sbin:/sbin), which won't include it unless it's baked in "
            "at build time."
        )
    claude_dir = str(Path(resolved_claude).resolve().parent)

    app = dist_dir / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)

    macos_dir = app / "Contents" / "MacOS"
    resources_dir = app / "Contents" / "Resources"
    macos_dir.mkdir(parents=True)
    resources_dir.mkdir(parents=True)

    # build.json: which commit this bundle was built from. Kept OUTSIDE the
    # bundle (next to it in dist/) on purpose: the ad-hoc code signature's
    # cdhash seals every file inside the .app, and macOS TCC keys the
    # Microphone/Screen Recording/Automation grants on that cdhash — so if
    # build.json lived inside, every rebuild would silently revoke every
    # permission. With it outside, the bundle's bytes (launcher, plist,
    # icon) are identical build to build and the grants survive.
    build_json = dist_dir / "veronica-build.json"
    build_json.write_text(json.dumps(version_mod.build_info(run=run, env={}, repo=repo), indent=2) + "\n")

    # launcher: a native stub that embeds CPython (see STUB_SOURCE)
    launcher = macos_dir / APP_NAME
    libpython = libpython or _libpython_for(venv_python)
    defines = _launcher_defines(repo, venv_python, claude_dir, build_json, app.resolve(), libpython,
                                brain_dirs=_brain_dirs())
    (compiler or _compile_with_clang)(STUB_SOURCE, launcher, defines)
    launcher.chmod(launcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Info.plist
    version = _read_version(repo)
    with open(app / "Contents" / "Info.plist", "wb") as f:
        plistlib.dump(_info_plist(version), f)

    # PkgInfo
    (app / "Contents" / "PkgInfo").write_text("APPL????")

    # icon
    icns_src = repo / "assets" / f"{APP_NAME}.icns"
    if icns_src.exists():
        shutil.copy(icns_src, resources_dir / f"{APP_NAME}.icns")
    else:
        print(f"build_app: {icns_src} not found — run scripts/make_icon.py first; app will have no icon")

    if codesign_enabled:
        if shutil.which("codesign") is None:
            print("build_app: codesign not available — skipping ad-hoc signing")
        else:
            identity = signing_identity()
            subprocess.run(
                ["codesign", "--force", "--deep", "-s", identity, str(app)],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
            )
            if identity == "-":
                print("build_app: ad-hoc signed — macOS will ask for Microphone and Screen "
                      "Recording again after a change. Run ./scripts/make_signing_cert.sh once "
                      "to sign with a stable certificate instead.")

    return app


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--no-codesign", action="store_true", help="skip ad-hoc codesign")
    args = p.parse_args(argv)
    app = build_app(codesign_enabled=not args.no_codesign)
    print(f"build_app: wrote {app}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
