"""Build dist/Veronica/Veronica.exe: a one-folder, windowed PyInstaller build of
`python -m veronica` (system tray app, no console window).

Layout:

    dist/Veronica/
        Veronica.exe            PyInstaller bootloader + the generated entry script (ENTRY_SOURCE)
        _internal/              Python, the dependencies, and veronica itself, including its
                                 data files (veronica/ui/** web pages, veronica/browser_extension/**)
        _internal/build.json    {sha, built_at, dirty, source, repo} from git at build time

The entry script exports VERONICA_BUNDLE_BUILD (that build.json) so
veronica.version reports the commit that was built rather than whatever the
checkout has moved on to, exports VERONICA_REPO and changes into the checkout
(so `.env` and the updater work exactly as in `uv run python -m veronica`),
and understands `Veronica.exe -m <module> …` — the brains start Veronica's
MCP tool server and hook as `sys.executable -m veronica.…`, and in the frozen
app sys.executable is Veronica.exe.

Speech/wake models are NOT bundled: they live in ~/.veronica/models
(scripts/download_models.py), shared by dev runs and the built app.

The build runs PyInstaller with the checkout's own venv (.venv\\Scripts\\python.exe,
`uv sync --extra dev` installs it) into build/pyinstaller/, then swaps the result
into dist/Veronica. If the running Veronica.exe holds the old folder open
(an in-app update), the new build is left as dist/Veronica.new instead and
the relaunch helper (veronica.ui.relaunch) swaps it in once the app has quit.

Signing is optional: `signtool sign /fd SHA256 /a dist\\Veronica\\Veronica.exe`
(Windows SDK) with a code-signing certificate keeps SmartScreen quieter; an
unsigned build runs fine on the machine that built it.

Run directly (Windows):

    uv run python scripts/build_app.py
"""
from __future__ import annotations

import argparse
import contextlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

from veronica import version as version_mod

REPO = Path(__file__).resolve().parent.parent
APP_NAME = "Veronica"
STAGED_SUFFIX = ".new"   # keep in step with veronica.ui.relaunch.STAGED_SUFFIX

# Packages whose non-Python files (models' configs, onnx assets, espeak data,
# DLLs) PyInstaller's import analysis can't see. `--collect-all` for the ones
# shipping binaries, `--collect-data` for data-only ones; a package that isn't
# installed only earns a warning.
COLLECT_ALL = ("webview", "pystray", "espeakng_loader", "claude_agent_sdk", "winrt")
COLLECT_DATA = ("veronica", "faster_whisper", "openwakeword", "kokoro_onnx", "language_tags", "phonemizer")
HIDDEN_IMPORTS = ("pystray._win32", "webview.platforms.winforms", "webview.platforms.edgechromium",
                  "comtypes.stream", "pycaw.pycaw")

ENTRY_SOURCE = '''"""Veronica.exe entry point -- generated by scripts/build_app.py."""
import json
import os
import runpy
import sys
from pathlib import Path


def _bundle_dir() -> Path:
    return Path(getattr(sys, "_MEIPASS", Path(sys.executable).parent))


def _setup() -> None:
    build_json = _bundle_dir() / "build.json"
    os.environ.setdefault("VERONICA_BUNDLE_BUILD", str(build_json))
    try:
        repo = json.loads(build_json.read_text(encoding="utf-8")).get("repo") or ""
    except (OSError, ValueError):
        repo = ""
    if repo and Path(repo).is_dir():
        os.environ.setdefault("VERONICA_REPO", repo)
        # .env and relative paths resolve as in `uv run python -m veronica`.
        os.chdir(repo)


def main() -> None:
    _setup()
    # `Veronica.exe -m veronica.tools.serve ...`: what `python -m` would do.
    if len(sys.argv) >= 3 and sys.argv[1] == "-m":
        module = sys.argv[2]
        sys.argv = [sys.argv[0], *sys.argv[3:]]
        runpy.run_module(module, run_name="__main__", alter_sys=True)
        return
    from veronica.__main__ import main as veronica_main
    veronica_main(sys.argv[1:])


if __name__ == "__main__":
    import multiprocessing

    multiprocessing.freeze_support()
    main()
'''


def _venv_python(repo: Path) -> Path:
    if sys.platform == "win32":
        return repo / ".venv" / "Scripts" / "python.exe"
    return repo / ".venv" / "bin" / "python"


def _write_build_json(path: Path, repo: Path, run) -> dict:
    info = dict(version_mod.build_info(run=run, env={}, repo=repo))
    info["repo"] = str(repo)
    path.write_text(json.dumps(info, indent=2) + "\n", encoding="utf-8")
    return info


def pyinstaller_argv(python: Path, entry: Path, *, repo: Path, work: Path, staging: Path,
                     build_json: Path, icon: Path | None) -> list[str]:
    argv = [
        str(python), "-m", "PyInstaller", str(entry),
        "--noconfirm", "--clean", "--onedir", "--windowed",
        "--name", APP_NAME,
        "--distpath", str(staging), "--workpath", str(work / "work"), "--specpath", str(work),
        "--paths", str(repo),
        "--add-data", f"{build_json}{os.pathsep}.",
        "--collect-submodules", "veronica",
    ]
    for pkg in COLLECT_ALL:
        argv += ["--collect-all", pkg]
    for pkg in COLLECT_DATA:
        argv += ["--collect-data", pkg]
    for mod in HIDDEN_IMPORTS:
        argv += ["--hidden-import", mod]
    if icon is not None:
        argv += ["--icon", str(icon)]
    return argv


def _install(new: Path, target: Path) -> Path:
    """Swap the fresh build `new` into `target` (dist/Veronica). If `target`
    is in use — the running app's exe/DLLs are locked — stage it as
    dist/Veronica.new for the relaunch helper instead. Returns where the new
    build now is."""
    staged = target.with_name(target.name + STAGED_SUFFIX)
    if staged.exists():
        shutil.rmtree(staged, ignore_errors=True)
    if not target.exists():
        shutil.move(str(new), str(target))
        return target
    old = target.with_name(f"{target.name}.old-{int(time.time())}")
    try:
        # A rename is all-or-nothing, unlike rmtree, which would leave a
        # half-deleted install behind when it hits a locked file.
        target.rename(old)
    except OSError:
        shutil.move(str(new), str(staged))
        print(f"build_app: {target} is in use — staged the new build at {staged}; "
              "it's swapped in when Veronica restarts")
        return staged
    shutil.move(str(new), str(target))
    shutil.rmtree(old, ignore_errors=True)
    return target


def build_app(
    *,
    repo: Path = REPO,
    dist_dir: Path | None = None,
    venv_python: Path | None = None,
    run=subprocess.run,
) -> Path:
    """Build dist/Veronica/Veronica.exe (or dist_dir/Veronica/Veronica.exe)
    and return the exe's final path. `run` runs git (build.json) and
    PyInstaller — injectable for tests. Raises RuntimeError on failure."""
    dist_dir = dist_dir or (repo / "dist")
    python = venv_python or _venv_python(repo)
    if not python.exists():
        raise RuntimeError(f"build_app: {python} not found — run `uv sync --extra dev` first")

    work = repo / "build" / "pyinstaller"
    staging = work / "dist"
    if staging.exists():
        shutil.rmtree(staging)
    work.mkdir(parents=True, exist_ok=True)

    build_json = work / "build.json"
    _write_build_json(build_json, repo, run)
    entry = work / "veronica_entry.py"
    entry.write_text(ENTRY_SOURCE, encoding="utf-8")

    icon = repo / "assets" / f"{APP_NAME}.ico"
    if not icon.exists():
        print(f"build_app: {icon} not found — run scripts/make_icon.py first; the exe will have no icon")
        icon = None

    argv = pyinstaller_argv(python, entry, repo=repo, work=work, staging=staging, build_json=build_json, icon=icon)
    kwargs: dict = {"cwd": repo, "capture_output": True, "text": True, "check": False}
    if sys.platform == "win32":
        kwargs["creationflags"] = 0x08000000   # CREATE_NO_WINDOW (run from the windowless app)
    done = run(argv, **kwargs)
    if done.returncode != 0:
        tail = "\n".join((done.stderr or done.stdout or "").strip().splitlines()[-20:])
        raise RuntimeError(f"build_app: PyInstaller failed ({done.returncode}):\n{tail}")

    built = staging / APP_NAME
    if not (built / f"{APP_NAME}.exe").exists():
        raise RuntimeError(f"build_app: PyInstaller did not produce {built / (APP_NAME + '.exe')}")
    dist_dir.mkdir(parents=True, exist_ok=True)
    target = dist_dir / APP_NAME
    _install(built, target)
    with contextlib.suppress(OSError):
        staging.rmdir()
    return target / f"{APP_NAME}.exe"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.parse_args(argv)
    exe = build_app()
    print(f"build_app: wrote {exe}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
